FROM node:16.13.2

RUN mkdir -p /project
WORKDIR /project

USER node

RUN npm config set prefix /home/node/.npm-packages
ENV PATH="${PATH}:/home/node/.npm-packages/bin"

RUN npm install -g npm@latest
RUN npm install -g pnpm
RUN npm install -g npm-check-updates
RUN npm install -g concurrently
RUN npm install -g @nestjs/cli
RUN npm init vue@latest

{% if '.docker/node/.certs/*' is found_with_glob %}
USER root

{% if '.docker/node/.certs/.*' is found_with_glob %}
COPY .certs/.* /usr/local/share/ca-certificates/
RUN mv /usr/local/share/ca-certificates/.signer.crt /usr/local/share/ca-certificates/signer.crt
{% endif %}
COPY .certs/* /usr/local/share/ca-certificates/
RUN update-ca-certificates
ENV NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt

USER node
{% endif %}

RUN mkdir -p /home/node/.cache && chown -R node /home/node/.cache
RUN mkdir -p /home/node/.npm && chown -R node /home/node/.npm

VOLUME /project
VOLUME /home/node/.cache