FROM httpd:2.4

RUN echo >> /usr/local/apache2/conf/httpd.conf && echo 'Include conf/custom/*.conf' >> /usr/local/apache2/conf/httpd.conf

RUN sed -i '/LoadModule proxy_module/s/^#//g' /usr/local/apache2/conf/httpd.conf \
&& sed -i '/LoadModule proxy_http_module/s/^#//g' /usr/local/apache2/conf/httpd.conf \
&& sed -i '/LoadModule headers_module/s/^#//g' /usr/local/apache2/conf/httpd.conf \
&& sed -i '/LoadModule rewrite_module/s/^#//g' /usr/local/apache2/conf/httpd.conf